name: chat_gpt_sdk
description: create chat bot and other bot with ChatGPT SDK Support GPT-4 , 3.5 and SSE Generate Prompt (Stream)
version: 3.1.3
homepage: https://www.facebook.com/REDEVRX
repository: https://github.com/redevRx/Flutter-ChatGPT

environment:
  sdk: ^3.5.3
#  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  dio_compatibility_layer: ^0.1.0
  fetch_client: ^1.1.2
  http_parser: ^4.0.0
#  path_provider: ^2.1.4

dev_dependencies:
  mockito: ^5.4.1
  build_runner: ^2.4.4
  lints: ^4.0.0
  coverage: ^1.7.2
  test: ^1.25.2
